name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '7.4/**'
      - '8.0/**'
      - '8.1/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [7.4-bullseye, 8.0-bullseye, 8.1-bullseye]
        include:
          - version: 7.4-bullseye
            docker-context: 7.4/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:7.4-apache
              nicoherbigde/typo3-cms-php:7.4-apache-bullseye
              nicoherbigde/typo3-cms-php:7.4.33-apache
              nicoherbigde/typo3-cms-php:7.4.33-apache-bullseye
          - version: 8.0-bullseye
            docker-context: 8.0/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:8.0-apache
              nicoherbigde/typo3-cms-php:8.0-apache-bullseye
              nicoherbigde/typo3-cms-php:8.0.26-apache
              nicoherbigde/typo3-cms-php:8.0.26-apache-bullseye
          - version: 8.1-bullseye
            docker-context: 8.1/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:8.1-apache
              nicoherbigde/typo3-cms-php:8.1-apache-bullseye
              nicoherbigde/typo3-cms-php:8.1.13-apache
              nicoherbigde/typo3-cms-php:8.1.13-apache-bullseye

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
